language: node_js
node_js:
- 8
cache:
  directories:
  - node_modules
script:
- npm run test
deploy:
  provider: heroku
  api_key:
    secure: fHNilFnntB2X2LDZY8oeKGYZY5f/gJllroTyPk8NOjHENW+FiDNQrhk5f9JnPSdfAqQ6RHVNcdvDfz5GXE3jA/4whNlHJJNETOX6s4+CKdg/SEYuqMH0qPkuPKFDG0NU6YKVztxiKDAQ9V8YkzCK4oiUAbImTBklZ+m44Z6ANKpPwtEeEVSCAhPVOQ7+2CI18sdb+eZCmDbZBBbGoqfUIHzAYDDotmKXRERb0v2P2zjhDgnnhwN2q6TzqgjiQqcp3hsv7miFxKcYZbNGOBrQlNmeKWEXjpERgAL9KpxTL8Y37bYw+fjIi75FV9vxEPRd5ZCpiqCyVlJdVUZgbSZ/hoPM6bBixV2E1X6e6R0pNFGrJggbzzbLv6GDuiEEq2sXSk94eSiCKAT9usJ+4u9o6dFKMzQRKbxG8vn+Ht2FTEj2iL9Gq10ga5Jl9tdBBglMqRBxzcHH561+9R7bWyppEEmXgBUQTg93JhmTspg1yKKkAUNJTVbWlYcN+S4ThT5bdmTmZhq51mCIKsuIWN6j7cSh41Ts+cuKqbvwokdMD9UNWhfS6OxWjyii8OhfnlnQqcX0Evhk67QWX9YCTP5vaTF9Yd+xjrtiravO8c1JSRWSX5u/MbMWESpAep8GnaVoNFNuIytDQD9LUHYuw1Dg9bY9sBPUKYHBslKr90W3k7A=
  app: trackflix
  on:
    repo: kevgathuku/trackflix
