language: node_js
node_js:
- 10
cache:
  yarn: true
  directories:
  - node_modules
script:
- cd client && yarn && npm run test
notifications:
  email:
    on_success: change
deploy:
  provider: heroku
  api_key:
    secure: nG4skrnu2ugUtQMrIL8fpCK/fflL5r79z2lBVg65iW488OyQdOyCnqwEhrtMSooL3fzbfCPVtQ4cLZ/9yZZp/Cm5TdUlFTZRM47UuSzNWRktrzpBNcU68I+2aWlwtp0Hfj6kVrrXukIhr4f8UWgkQbVUx6UVu8CXHxDAa+pTYUDB/p0iOamx2bi27eu9S2vTSKmcdW/NkY5IUgqFfOeQyMBJEfdhURoyzLAe3wTTOyuALFT2wJQGBOOyACvetlpmeRhOC9QA2CsWoQ3GjWrGgfKmQkG204j6Y/3hNeVytEPwCgRq9Qls0z90r3A3+phvOJVw6IE0CiYw6uShytd9w0o6p9B351brM7FBc+SPUbLJbLoU5ypSoIAEzstr2c2uz1W2Rb23mcZqeQAtpAgnkpsYShF2Cdh29ZjXyF4AhcMDBinlrENGZ7kqZ0oxCUoZ4hStGEWQlwisrIDbc4WiA2khoB8MOKUMqO6nxYKIIN9mWW6wg0/9Kud1H47HU+kyxmbhAPaeDL9gByyOBUWoqH37HLjijVgbcUsmZ9DZ0ceGkOQO/urUfwnleE2q3FjsnNPamY16vs5Xv8LUs8yUoi7EcwhgdlcklpW0kA4VURASUmmjrWqn5D2I95tKr3Z+Bf9vL4LRRKuk3JQ0WYlu3FIN/QXsthAexp7sj+Co4w0=
  app: trackflix
  on:
    repo: kevgathuku/trackflix
