// flow-typed signature: b28a905cb3ccc3618d4d5f4b09267cf0
// flow-typed version: <<STUB>>/tachyons_v4.10.0/flow_v0.81.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'tachyons'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'tachyons' {
  declare module.exports: any;
}
